files:
  - source: '*.xml'
    ignore:
      - '**/strings/*.xml'
      - '*_not_translated.xml'
      - '*_size_mismatch.xml'
      - '**-%locale_with_underscore%/*.xml'
      - /MIUI14-HyperOS/**/*.xml
      - /diting/**/*.xml
      - /fuxi/**/*.xml
      - /ingres/**/*.xml
      - /ishtar/**/*.xml
      - /mayfly/**/*.xml
      - /mondrian/**/*.xml
      - /multilang_filter/**/*.xml
      - /nuwa/**/*.xml
      - /shennong/**/*.xml
      - /socrates/**/*.xml
      - /thor/**/*.xml
      - /unicorn/**/*.xml
      - /zeus/**/*.xml
    translation: /%original_path%-%android_code%/%original_file_name%
